### ISSUE TITLE
Use the assets of the UD-Viz package instead of copying them

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Demo-DatAgora-Deambulation-Bron#5]
We actually point to a local cloned version of UD-Viz for the assets.

Two possible scenarios:
 1. it is **NOT** a good practice to pack assets within UD-VIZ then
    - remove the assets from UD-Viz 
    - clone the new repository of UD-Viz assets here
  2. it is a good practice to pack assets within UD-VIZ then learn how to the assets packaged within UD-Viz and avoid a clone of the UD-Viz repository.

**Comment by webanck** [comment]
When listing UD-Viz as a npm dependency of eg a demo (inside file `package.json`) and after doing `npm install`, the `node_modules/ud-viz` directory doesn't contain any asset. From my understanding, the assets are thus currently not included within the npm package.

Instead of recovering the required assets from the UD-Viz repository to recover the required assets, those could be downloaded manually.
Another approach would be to put the assets somewhere else, in a LIRIS dataset such as [this one](https://dataset-dl.liris.cnrs.fr/vcity-sample-data/bron-2018-campus/) which already stores the specific models  (`campus.glb` and `map.glb`) of this `UD-Demo-DatAgora-Deambulation-Bron` repository.

My only fear is that decoupling assets from the code using them might lead to a situation where the assets are not available or do not fit the code anymore.
There is the `git-lfs` solution but the free plan proposed by github is very restricted to be reasonably usable. I would suggest a competitor to `git-lfs` : [`git-annex`](https://git-annex.branchable.com/). It provides a smart and light way to track the binary data and its versions used by a repository through hashes and to register the multiple and heterogeneous sources where the data can be downloaded.

**Comment by EricBoix** [comment]
Asset shipping seems to still be a [hot topic](https://github.com/webpack/webpack/issues/7353). And we cannot hope for UD-Viz to decide their asset distribution strategy before the deadline.
What is the weight (and number) of the UD-VIZ assets you depend on ? Because if this happens to be "small" (your measure may vary) then maybe copying them to this repository might prove to be the simplest way although quite dirty/kludgy (because the [DRY principle](https://en.wikipedia.org/wiki/Don't_repeat_yourself) won't be respected AND because git repositories are not supposed to host data but only code).

**Comment by webanck** [comment]
Assets are now all downloaded from the LIRIS dataset https://dataset-dl.liris.cnrs.fr/vcity-sample-data/bron-2018-campus/ at installation (see `getAssets.sh` script).
